# Generated by Django 4.1.4 on 2023-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marriagesurvey_anycommond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagesurvey',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='agree_buying_house',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='anycommond',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='is_married',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='marriage_intention',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marriagesurvey',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
