# Generated by Django 4.1.4 on 2023-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_marriagesurvey_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagesurvey',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
